# Biscuits au chocolat, aux amandes et au caramel

## Ingrédients

### Section TODO

- 225 g farine tout usage non blanchie
- 50 g cacao
- 2.5 ml bicarbonate de soude
- 1 ml sel
- 170 g beurre non salé, fondu et tempéré
- 160 g cassonade
- 105 g sucre
- 45 ml beurre d’amandes
- 2 unité œufs
- 250 g chocolat au lait, en pastilles ou haché grossièrement
- 130 g amandes, grillées et hachées
- 20 unité caramels mous du commerce
- 1 au goût fleur de sel

## Préparation

### Section TODO

- Dans un bol, mélanger la farine, le cacao, le bicarbonate et le sel.

- Dans un autre bol, mélanger le beurre, la cassonade, le sucre et le beurre d’amandes au batteur électrique.

- Ajouter les œufs, un à la fois, puis mélanger 5 minutes. À basse vitesse, incorporer les ingrédients secs, 170 g du chocolat et 85 g des amandes.

- À l’aide d’une cuillère à crème glacée de 45 ml, former des boules de pâte et les répartir sur une plaque tapissée de papier parchemin. Réfrigérer la pâte de 5 à 10 minutes.

- Insérer un caramel au centre de chaque boule de pâte et refermer la pâte pour reformer une boule.

- Ajouter le reste du chocolat et des amandes sur les boules de pâte. Réfrigérer 2 heures ou congeler à cette étape, si désiré.

- Préchauffer le four à 190 °C. Tapisser deux plaques de cuisson de papier parchemin.

- Répartir de 6 à 8 biscuits par plaque.

- Cuire au four, une plaque à la fois, de 8 à 10 minutes, jusqu’à ce que les biscuits soient cuits à l’extérieur mais encore mous au centre.

- Parsemer de fleur de sel et laisser tiédir sur la plaque.

## Notes

- Il est possible d’ajouter tout le chocolat et les amandes à l’étape du mélange, mais en conserver une partie pour le dessus rend les biscuits plus jolis.
- Un repos de 2 heures au réfrigérateur permet d’éviter que les biscuits ne s’étalent trop à la cuisson.
- La pâte peut reposer jusqu’à 12 heures au réfrigérateur pour une meilleure absorption des liquides.
- Les biscuits se conservent 3 jours à température ambiante ou 3 mois au congélateur.
