# Brioche à la cannelle (patate)

## Ingrédients

### Brioches

- 1 grosse pomme de terre, non pelée (ou 2 moyennes)
- 250 ml (1 tasse) de lait, tiède
- 105 g (1/2 tasse) de sucre
- 715 g (4 3/4 tasses) de farine tout usage non blanchie
- 12,5 ml (2 1/2 c. à thé) de levure instantanée
- 5 ml (1 c. à thé) de sel
- 2 oeufs
- 55 g (1/4 tasse) de beurre non salé, fondu
- 45 ml (3 c. à soupe) d’huile de canola

### Garniture
- 315 g (1 1/2 tasse) de cassonade
- 15 ml (1 c. à soupe) de cannelle moulue
- 30 ml (2 c. à soupe) de beurre non salé, fondu
- Lait, pour badigeonner

### Glaçage
- 135 g (1 tasse) de sucre à glacer
- 15 ml (1 c. à soupe) de lait

## Préparation

### Brioches

- Dans une petite casserole d’eau bouillante, cuire la pomme de terre jusqu’à ce qu’elle soit tendre. Égoutter, peler et piler la pomme de terre à l’aide d’un pressepurée ou d’un pilon. Vous aurez besoin de 250 ml (1 tasse) de purée de pommes de terre. Réserver.

- Dans un bol, mélanger le lait et le sucre. Réserver.

- À la cuillère de bois ou dans un batteur sur socle, (en utilisant le crochet à pétrir), mélanger la farine, la levure et le sel. Ajouter le mélange de lait, les oeufs, la pomme de terre et mélanger vigoureusement jusqu'à ce que la pâte commence à se former.

- Incorporer le beurre et l’huile graduellement et pétrir la pâte environ 5 minutes au batteur sur socle ou sur un plan de travail fariné. La pâte sera molle et légèrement collante. Déposer la pâte dans un bol propre et légèrement huilé. Couvrir le bol d’un linge légèrement humide et laisser reposer dans un endroit tiède et humide pendant environ 20 minutes.

### Garniture

- Dans un bol, mélanger la cassonade et la cannelle. Réserver.

- Sur un plan de travail généreusement fariné, abaisser la pâte pour obtenir un rectangle de 50 x 35 cm (20 x 14 po). Badigeonner de beurre fondu et répartir le mélange de cassonade sur toute la surface de la pâte. Rouler la pâte fermement pour obtenir un cylindre de 50 cm (20 po) de long.

- Couper le rouleau en 12 tranches. Pour ce faire, glisser un fil de soie dentaire sans saveur sous le cylindre. Le croiser sur le dessus en tirant de façon à ce qu’il coupe la pâte.

- Répartir les tranches à plat dans un moule en pyrex beurré de 33 x 23 cm (13 x 9 po). Laisser lever, sans couvrir, dans un endroit tiède et humide environ 1 h 30 ou jusqu’à ce que les brioches soient gonflées et se touchent.

- Placer la grille au centre du four. Préchauffer le four à 180°C (350°F). Badigeonner les brioches de lait. Cuire au four environ 30 minutes ou jusqu’à ce que les brioches soient dorées. Laisser tiédir.

### Glaçage

- Dans un bol, mélanger le sucre et le lait jusqu’à ce que le mélange soit homogène. Ajouter du lait au besoin. Au moment de servir, glacer les brioches.

## Notes Ricardo

- Pour les préparer la veille, il suffit de couvrir d'une pellicule de plastique le plat en pyrex contenant les brioches non levées et de le réfrigérer jusqu'au lendemain. Retirez la pellicule de plastique et faites les lever comme à l'habitude dans un endroit tiède et humide ou, pour accélérer le processus, déposez le plat en pyrex dans un bain d'eau chaude.
