name: Setup R + renv + livrec
description: Install R, restore renv cache, and install livrec with its dependencies.
inputs:
  r-version:
    description: R version to install
    required: false
    default: '4.5.2'
runs:
  using: composite
  steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ inputs.r-version }}

    - name: Restore R packages with renv
      uses: r-lib/actions/setup-renv@v2

    - name: Install livrec package and dependencies
      shell: bash
      run: |
        Rscript -e 'source("renv/activate.R"); deps <- unique(na.omit(renv::dependencies("livrec")$Package)); deps <- setdiff(deps, "livrec"); if (length(deps) > 0) renv::install(deps, prompt = FALSE, repos = "https://cloud.r-project.org"); renv::install("./livrec", prompt = FALSE)'
